import { Router } from 'express';
import { getPool, sql } from '../db/pool';
import { asyncHandler, badRequest, ok, listOk, notFound } from '../utils/http';
import { ClientIntegrationCreate, ClientIntegrationUpdate } from '../validation/schemas';

const router = Router();
router.get('/', asyncHandler(async (req, res) => { const { page, limit, offset } = (await import('../utils/http')).getPagination(req); const pool = await getPool(); const r = await pool.request().input('offset', sql.Int, offset).input('limit', sql.Int, limit).query(`SELECT integration_id, client_id, integration_code, status, config_json FROM app.client_integrations ORDER BY integration_id OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`); listOk(res, r.recordset, { page, limit, total: r.recordset.length }); }));
router.get('/:id', asyncHandler(async (req, res) => { const id = Number(req.params.id); if (Number.isNaN(id)) return badRequest(res, 'id must be int'); const pool = await getPool(); const r = await pool.request().input('id', sql.Int, id).query(`SELECT integration_id, client_id, integration_code, status, config_json FROM app.client_integrations WHERE integration_id=@id`); const row = r.recordset[0]; if (!row) return notFound(res); ok(res, row); }));
router.post('/', asyncHandler(async (req, res) => { const parsed = ClientIntegrationCreate.safeParse(req.body); if (!parsed.success) return badRequest(res, parsed.error.issues.map(i=>i.message).join('; ')); const { client_id, integration_code, status = 'waiting', config_json = null } = parsed.data; const pool = await getPool(); await pool.request().input('client_id', sql.Int, client_id).input('integration_code', sql.NVarChar(80), integration_code).input('status', sql.NVarChar(40), status).input('config_json', sql.NVarChar(sql.MAX), config_json).query(`INSERT INTO app.client_integrations (client_id, integration_code, status, config_json) VALUES (@client_id, @integration_code, @status, @config_json)`); const read = await pool.request().query(`SELECT TOP 1 integration_id, client_id, integration_code, status, config_json FROM app.client_integrations ORDER BY integration_id DESC`); ok(res, read.recordset[0], 201); }));
router.put('/:id', asyncHandler(async (req, res) => { const id = Number(req.params.id); if (Number.isNaN(id)) return badRequest(res, 'id must be int'); const parsed = ClientIntegrationUpdate.safeParse(req.body); if (!parsed.success) return badRequest(res, parsed.error.issues.map(i=>i.message).join('; ')); const data = parsed.data; const sets: string[] = []; const pool = await getPool(); const request = pool.request().input('id', sql.Int, id); if (data.integration_code !== undefined) { sets.push('integration_code=@integration_code'); request.input('integration_code', sql.NVarChar(80), data.integration_code); } if (data.status !== undefined) { sets.push('status=@status'); request.input('status', sql.NVarChar(40), data.status); } if (data.config_json !== undefined) { sets.push('config_json=@config_json'); request.input('config_json', sql.NVarChar(sql.MAX), data.config_json); } if (!sets.length) return badRequest(res, 'No fields to update'); const result = await request.query(`UPDATE app.client_integrations SET ${sets.join(', ')} WHERE integration_id=@id`); if (result.rowsAffected[0]===0) return notFound(res); const read = await pool.request().input('id', sql.Int, id).query(`SELECT integration_id, client_id, integration_code, status, config_json FROM app.client_integrations WHERE integration_id=@id`); ok(res, read.recordset[0]); }));
router.delete('/:id', asyncHandler(async (req, res) => { const id = Number(req.params.id); if (Number.isNaN(id)) return badRequest(res, 'id must be int'); const pool = await getPool(); const r = await pool.request().input('id', sql.Int, id).query(`DELETE FROM app.client_integrations WHERE integration_id=@id`); if (r.rowsAffected[0]===0) return notFound(res); ok(res, { deleted: r.rowsAffected[0] }); }));
export default router;
