name: Deploy API to Azure Function App

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: flowledger-api-func
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'api'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install dependencies and build'
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          npm install
          npm run build --if-present

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A40621D3D83D45A295A0D8630E541A3C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5A9A63E97B234521898083D9792CEEF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0DE7B13A2C1B4E44A494B445725E7716 }}

      - name: 'Deploy to Azure Function App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

