name: Build and deploy Node app to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (api)
        working-directory: ./api
        run: npm ci

      - name: Build (api)
        working-directory: ./api
        run: npm run build

      - name: Package app
        run: |
          # package only the built output and runtime files
          rm -f deploy.zip || true
          cd api
          zip -r ../deploy.zip dist package.json package-lock.json -x "**/node_modules/**" >/dev/null

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: flowledger-api-web
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy.zip
