# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - flowledger-api-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (api)
        working-directory: ./api
        run: npm ci --no-audit --no-fund

      - name: Build (api)
        working-directory: ./api
        run: npm run build

      - name: Package app (zip dist + package.json)
        run: |
          rm -f deploy.zip || true
          cd api
          # create a temporary deployment folder with compiled output and a minimal runtime package.json
          rm -rf ../deploy_tmp || true
          mkdir -p ../deploy_tmp
          cp -R dist ../deploy_tmp/
          # include package-lock if present to help deterministic installs
          if [ -f package-lock.json ]; then cp package-lock.json ../deploy_tmp/; fi
            cat > ../deploy_tmp/package.json <<'JSON'
            {
              "name": "flowledger-api",
              "version": "0.1.0",
              "main": "dist/server.js",
              "engines": { "node": "20.x" },
              "scripts": { "start": "node dist/server.js" }
            }
            JSON
          # zip the prepared deploy_tmp folder contents (package.json at root + dist)
          cd ../deploy_tmp
          zip -r ../deploy.zip . -x "**/node_modules/**" >/dev/null
          cd ..
          rm -rf deploy_tmp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_23C8370738634DA49E74C260F72B2AEF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7A2BFF6ACEB54D4E9F29C6173F318D85 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0D32C3D9A50D4DDE895C7C7982CB276E }}

      - name: Deploy to Azure Web App (ZIP)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'flowledger-api-web'
          slot-name: 'Production'
          package: ./deploy.zip
